language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

os:
  - linux

stages:
  - test
  - name: deploy
    if: tag IS PRESENT AND repo = equinor/camille

matrix:
  fast_finish: true
  include:
  - name: OSX Python 3.7
    os: osx
    osx_image: xcode9.4
    language: generic

  - name: OSX Python 3.8
    os: osx
    osx_image: xcode11.5
    language: generic

  - name: Manylinux
    stage: deploy
    python: 3.6
    dist: xenial
    sudo: true
    env:
      - PYPI_BUILD: true
      - CIBW_BUILD: '''cp35-manylinux_x86_64 cp36-manylinux_x86_64 cp37-manylinux_x86_64 cp38-manylinux_x86_64'''
      - CIBW_BEFORE_ALL: '''yum install -y gcc ninja-build'''
      - CIBW_BEFORE_BUILD: '''pip install cmake setuptools-scm -r requirements.txt && pip install --force-reinstall -r requirements-dev.txt'''
    install: 
      - pip3 install setuptools-scm cibuildwheel==1.5.5
      - pip3 install -r requirements.txt
      - pip3 install --force-reinstall -r requirements-dev.txt
    before_script: 'true'
    script: python3 -m cibuildwheel --output-dir dist
    after_success: 'true'
#  - name: Windows
#    stage: deploy
#    os: windows
#    language: shell
#    env:
#      - PYPI_BUILD: true
#      - CIBW_BUILD: '''cp35-win_amd64 cp36-win_amd64 cp37-win_amd64 cp38-win_amd64'''
#      - CIBW_BEFORE_BUILD: '''pip3 install cmake setuptools-scm -r requirements.txt && pip3 install --force-reinstall -r requirements-dev.txt'''
#      - PATH: /c/Python36:/c/Python36/Scripts:$PATH
#    before_install:
#      - choco install python --version 3.6.0
#      - python -m pip install --upgrade pip
#    install: pip install twine setuptools-scm cibuildwheel==1.5.5
#    before_script: 'true'
#    script: python -m cibuildwheel --output-dir dist
#    after_success: 'true'
  - name: MacOS
    stage: deploy
    os: osx
    language: shell
    env:
      - PYPI_BUILD: true
      - CIBW_BUILD: '''cp38-macosx_x86_64'''
      - CIBW_BEFORE_BUILD: '''pip3 install cmake setuptools-scm -r requirements.txt && pip3 install --force-reinstall -r requirements-dev.txt'''
    before_install: python3 -m pip install --upgrade pip
    install: pip3 install twine pathlib setuptools-scm cibuildwheel==1.5.5
    before_script: 'true'
    script: python3 -m cibuildwheel --output-dir dist
    after_success: 'true'

install:
  - pip3 install -r requirements.txt
  - pip3 install bandit setuptools-scm
  - pip3 install coverage codacy-coverage

before_script:
  - bandit -c bandit.yml -r camille

script:
  - pip3 install --force-reinstall -r requirements-dev.txt
  - python3 setup.py build_ext --inplace
  - python3 setup.py test --verbose

after_success:
  - 'if [ ! -z "${CODACY_PROJECT_TOKEN}" ]; then coverage run setup.py test; coverage xml; python-codacy-coverage -r coverage.xml; fi'

deploy:
#  - provider: pypi
#    skip_cleanup: true
#    on:
#      condition: $PYPI_BUILD = true
#      repo: equinor/camille
#      tags: true
#    user: statoil-travis
#    password:
#      secure: jJbW5U0BuXbuTnlsZD7nKRKDGFPkUSVGSnJy0FwZu3CQ2yEk9OUKtPoRS1kaEgVdxoYtCgZemRk1WfkkJqSklitFvrfpKU4WBbdQxUrmHjzaRYxe3dipaP4+CFM7nMG7YNwwScQfn1bocH2AaC/wIcBIoYkZWbJARc5V1NsbvxdEk5dPHaPRLaL4zxjHShfLTBKsUculn9jCwrjj9k35/JycF6hWXzWD+HC4q8oz743Q0oyjkcZu1zYHLns9Ug0lTCDjO4ugFXTcwlyKRXDepSwGy6Y6bwiU9d1/Jj/5TNU1tNkKWHHxjn15O2BWMt/aw97575g08FS+/ewprfRCfYGsXJskr5I5/emRKZ1GODBFkeM/UGzfoOo/9C57J3ULrJcgKsMBIsUabLyXswSpcVEaKTexTqnkEebkJfcwMxL4pz7uU8jHxYvg4gUvrXUrKMzWqwUavwxY4K22dsMtx0U6UlrExpbHvPdn/czDcLL6jyKMkJsfjFHNlNXDBCdI26zT8ldrJqATZpdS9lalnkMo3bw8oDMsuhzyPSbMH1oQ1lMDILllS37CEqN7O05lxYfGYRrbxLfUaxZkA0S/RXZP3KwusnkBHqGVbT/8MZN1woKjze25hKpk1tE9V9ZQIvgPtfC5s7L/T9FqEqlWrZPF2q4e+UydG/lyYThhjHo=
  - provider: pypi
    server: https://test.pypi.org/legacy/
    edge: # necessary for windows deploy, leaving until the merge to master
      source: native-api/dpl
      branch: z-quotes
    skip_cleanup: true
    skip_existing: true
    on:
      condition: $PYPI_BUILD = true
      repo: IvanKolesarEquinor/camille
      tags: true
    user: ikol
    password: 
      secure: AzxbYR96XkOblB4oBIytLBXyOsqNFLYwIvAkd9G2YE5f+4n+DgNasXMmbKHvmwZ1aNAzGFAVJMsie9eAswpLVg9Ak4mjykb0C6Gj6tlTRyiLwsj8FkEhIVZP9Mp5L/MKiZ/6hb6zTBcc0GwcvyHP5ckrEew9CYnnzP/tarO2a7bjDkyrnPU71LKLKamnyNHvetfb0V+VG5ljKfOtzEsU2//zg2xJxLfGzhZxlyPs+qmTm0zwOOkPp8A78ldoJrMEb3NOHpbogl7owimVxkacyjnY1rjcV9jwlHCvam29yCUfr/xYFnG9/FLD8pPo9WLIm35Zny3NB0RxYxIxPq2JOuX5pLXRRadPmreQ2QHgNGp3hCR5tF3voCgLzRmc6e1KlkN6oOqGNWkJv6pk21ARUIOsmCWvdYmvAB8wVEUEZ0XHD/1Yw1i84bNkG0pQiVN5G4z07T6t4njUAISnUpI8xHvFKWC/UzGQgKbxZK+8wnExsdyZdU0epLwweR0ec8hAIigkUpbFgooTXDT3QZOazs7rY4ygCrmrHgyD6JkVVUThtAolBldtKGt0f2zGqfP7wye0LcCkTIoUySeOGNWkNzx5NVp3ErCyIHhSAug9arhK+bK5R1DLZUid8dKLkDd5+yIOnOAczVC7i1Clm43znO09E8r8WhUXo+JEsrjnm90=