version: 2.1

commands:

  bootstrap_macos:
    parameters:
      python-version:
        type: string
    steps:
      - run:
          name: Setup MacOS environment
          command: |
            # Get Conda
            curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh --silent
            bash Miniconda3-latest-MacOSX-x86_64.sh -b -f >> build.log
            # Install desired python script
            ~/miniconda3/bin/conda create -n py<< parameters.python-version >> python=<< parameters.python-version >> -y
            ln -s ~/miniconda3/envs/py<< parameters.python-version >>/bin/python ~/python<< parameters.python-version >>
            # Create appropriate virtual environment
            ~/python<< parameters.python-version >> -m venv py_venv


  install_macos_build_deps:
    steps:
      - run:
          name: Setup MacOS environment
          command: |
            . py_venv/bin/activate
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
            python -m pip install --force-reinstall -r requirements-dev.txt
            python -m pip install cmake setuptools-scm 

  python_build_test_macos:
    steps:
      - run:
          name: Build & test python
          command: |
            . py_venv/bin/activate
            python --version
            python -m pip freeze
            python setup.py build_ext --inplace
            python setup.py test --verbose

  install_build_deps:
    steps:
      - run:
          name: Install cmake, gcc, python3, git
          command: |
            sudo apt-get update
            sudo apt-get install \
            -y cmake g++ python3 python3-pip git 
    
  instal_python_deps:
    steps:
      - checkout
      - install_build_deps
      - run:
          name: Install python dependencies
          command: |
            python -m pip install --user -r requirements.txt
            python -m pip install --user -r requirements-dev.txt
            python -m pip install --user flake8 bandit setuptools-scm 
            python -m pip install --user coverage codacy-coverage

  flake8_req_check:
    steps:
      - run:
          name: Check code errors (pyflakes)
          command: flake8 --ignore=E --per-file-ignores="__init__.py:F401" .

  flake8_opt_check:
    steps:
      - run:
          name: Check formatting rules (PEP8)
          command: git diff HEAD^ | flake8 --diff --per-file-ignores="__init__.py:F401"

  bandit_check:
    steps:
      - run:
          name: Bandit security check
          command: bandit -c bandit.yml -r camille

  python_build_test:
    steps:
      - run:
          name: Build & test python
          command: |
            python --version
            pip freeze
            python setup.py build_ext --inplace
            python setup.py test --verbose

  codacy_check:
    steps:
      - run:
          name: Codacy code coverage check
          command: |
            if [ ! -z "${CODACY_PROJECT_TOKEN}" ]; then 
              coverage run setup.py test;
              coverage xml;
              python-codacy-coverage -r coverage.xml;
            fi

jobs:
  python-check:
    parameters:
      version:
        type: string
        default: "3.6"
      formatting:
        type: boolean
        default: false
    docker:
      - image: "circleci/python:<< parameters.version >>"
    steps:
      - instal_python_deps
      - when:
          condition: << parameters.formatting >>
          steps:
            - flake8_opt_check
      - unless:
          condition:  << parameters.formatting >>
          steps:
            - flake8_req_check
            - bandit_check
            - python_build_test
            - codacy_check

  macos-python-check:
    parameters:
      python-version:
        type: string
        default: "3.6"
    macos:
      xcode: 11.0.0
    steps:
      - checkout
      - bootstrap_macos:
          python-version: << parameters.python-version >>
      - install_macos_build_deps
      - python_build_test_macos

workflows:
  version: 2

  required:
    jobs:
      - python-check:
          name: Python 3.5
          version: "3.5"
          formatting: false
      - python-check:
          name: Python 3.6
          version: "3.6"
          formatting: false
      - python-check:
          name: Python 3.7
          version: "3.7"
          formatting: false
      - python-check:
          name: Python 3.8
          version: "3.8"
          formatting: false
  
  macos-tests:
    jobs:
      - macos-python-check:
          name: MacOS Python 3.5
          python-version: "3.5"
      - macos-python-check:
          name: MacOS Python 3.6
          python-version: "3.6"

  optional:
    jobs:
      - python-check:
          name: Python formatting check
          version: "3.8"
          formatting: true
